version: '3.1'
services:
  app:
    container_name: java-app
    image: springboot-postgresql
    ports:
      - "8082:8080"
    environment:
      - PORT=8082
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo